### ISSUE TITLE
Shitter can't interact with Fosstodon instance

### ISSUE THREAD

**Issue by Symbian9** [nuclearfog/Shitter#54]
Shitter 3.0.6 now just returns next notification on any action (refresh, post, etc.): 

> API does not support this operation!

It might happen due to Cloudflare protection turned ON since today by @fosstodon (due to DDoS attack on its host - @mastohost):

- https://github.com/fosstodon/hub/issues/5
  - Details: https://fosstodon.org/@kev/109953654645367614

Visiting Fosstodon using web browser now sometime even asks to resolve CAPTCHA:

![fosstodon](https://user-images.githubusercontent.com/13188580/222550238-b091792d-9e22-4531-a9ef-84a5b93ccb77.png)

**Comment by bleonard252** [comment]
Cloudflare's "I'm Under Attack Mode" breaks API/app access by turning up the security on everything by default. API clients (like apps) can't run JavaScript for the various Captchas and checks it's throwing out to fight the attack, since it's expecting JSON and not the HTML pages it's getting.

Basically, the only way to access Fosstodon at the moment is through the Web UI, behind all of its DDoS challenges like Captchas and browser checks.

**Comment by nuclearfog** [comment]
Is it now working?

**Comment by Symbian9** [comment]
Yes, seems like Fosstodon turned off emergency mode:

- https://fosstodon.org/@kev/109953810011169628
> Things are returning to normal now, so I've disabled "under attack mode" hopefully your apps will start working now too.

Closing for now.
